apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "klaytn.fullname" . }}
  labels:
    {{- include "klaytn.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
